version: '3'
services:
  backend:
    image: back
    ports:
      - "8000:8000"
    container_name: backend_service

  frontend:
    build: .
    ports:
      - "5173:5173"
    container_name: frontend_service
    depends_on:
      - backend
